site_name: Django Async Framework

theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: light blue
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/language-python
    favicon: material/language-python

nav:
  - Home: index.md
  - Quick Start: quickstart.md
  - Tutorial:    
      - AsyncView: tutorial/asyncview.md
      - AsyncAPIView: tutorial/asyncapiview.md
      - await_safe: tutorial/await_safe.md
      - run_in_background: tutorial/run_in_background.md
      - async_error_middleware: tutorial/async_error_middleware.md
  - About: about.md