name: Test, Build Docs, and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements/requirements-dev.txt
          pip install build twine mkdocs

      - name: Run tests
        run: pytest

      - name: Build docs
        run: mkdocs build

      - name: Deploy docs to GitHub Pages
        run: mkdocs gh-deploy --clean --force

      - name: Build package for PyPI
        run: |
          rm -rf dist/ build/ *.egg-info
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: twine upload dist/*
