name: Test and Deploy Docs

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install -r requirements/requirements-dev.txt

      - name: Run Makefile target
        run: make deploy
